apiVersion: v1
kind: Service
metadata:
  name: spacewalk-poc-service
spec:
  selector:
    app: spacewalk-poc
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: https
      protocol: TCP
      port: 8090
      targetPort: 443
    - name: clientpush
      protocol: TCP
      port: 9000
      targetPort: 5222
    - name: proxypush
      protocol: TCP
      port: 9050
      targetPort: 5269
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacewalk-poc
spec:
  selector:
    matchLabels:
      app: spacewalk-poc
  replicas: 1
  template:
    metadata:
      labels:
        app: spacewalk-poc
    spec:
      containers:
      - name: spacewalk-poc
        image: adityaworkspace/k8-spacewalk
        ports:
        - name: port80
          containerPort: 80
        - name: port443
          containerPort: 443
        - name: port68
          containerPort: 68
        - name: port69
          containerPort: 69
        - name: port5222
          containerPort: 5222
        - name: port5269
          containerPort: 5269
